Token=90091783796356575:0:mzzb8Ag3zuv9DIrthUXD6ta7OfuDBT
URI=wss://d1.nandbox.net:5020/nandbox/api/
DownloadServer=https://d1.nandbox.net:5020/nandbox/download/
UploadServer=https://d1.nandbox.net:5020/nandbox/upload/