name: CI

on:
  push:
    branches: [ "main" ]

jobs:
  call-build:
    uses: nandbox-bot/shared-ci/.github/workflows/build-ghcr.yml@main
    secrets:
      WEBHOOK_URL: ${{ secrets.WEBHOOK_URL }}